package installer_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// runDocCoverage runs scripts/doc-coverage.sh over a temp directory holding the
// given Go files (outside any git checkout, so the find fallback lists them),
// optionally with `awk` resolving to awkBin (e.g. mawk).
func runDocCoverage(t *testing.T, files map[string]string, awkBin string) (string, int) {
	t.Helper()
	script := filepath.Join(filepath.Dir(installShPath(t)), "scripts", "doc-coverage.sh")
	dir := t.TempDir()
	for name, content := range files {
		p := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	cmd := exec.Command("bash", script, dir)
	if awkBin != "" {
		bin := t.TempDir()
		if err := os.Symlink(awkBin, filepath.Join(bin, "awk")); err != nil {
			t.Fatal(err)
		}
		cmd.Env = append(os.Environ(), "PATH="+bin+string(os.PathListSeparator)+os.Getenv("PATH"))
	}
	out, err := cmd.CombinedOutput()
	code := 0
	if exitErr, ok := err.(*exec.ExitError); ok {
		code = exitErr.ExitCode()
	} else if err != nil {
		t.Fatalf("run: %v", err)
	}
	return string(out), code
}

// Exercises every declaration form the report counts, the godoc adjacency rule,
// and the skips (unexported, grouped blocks, tests, generated files).
var docCoverageFixture = map[string]string{
	"a.go": `package a

// Documented is a documented func.
func Documented() {}

func Undocumented() {}

// Detached is separated from its declaration by a blank line.

func Detached() {}

/* Block is documented with a block comment. */
func Block() {}

/*
MultiLine has a multi-line block comment.
*/
type MultiLine struct{}

// Method is a documented method.
func (m *MultiLine) Method() {}

func (m MultiLine) BareMethod() {}

// Generic is a method on a generic receiver.
func (s *Set[T]) Generic() {}

type Set[T any] struct{}

const Answer = 42

// Version is documented.
var Version = "1"

func unexported() {}

const (
	Grouped = 1
)
`,
	"a_test.go": "package a\n\nfunc TestHelper() {}\n",
	"gen.go":    "// Code generated by tool. DO NOT EDIT.\n\npackage a\n\nfunc Generated() {}\n",
}

func TestDocCoverageScript_CountsAndListsMissing(t *testing.T) {
	for _, awkBin := range []string{"", "/usr/bin/mawk"} {
		if awkBin != "" {
			if _, err := os.Stat(awkBin); err != nil {
				continue // mawk not installed here
			}
		}
		out, code := runDocCoverage(t, docCoverageFixture, awkBin)
		// Exported: Documented, Undocumented, Detached, Block, MultiLine,
		// Method, BareMethod, Generic, Set, Answer, Version = 11; missing:
		// Undocumented, Detached, BareMethod, Set, Answer = 5 → 54.5% < 80%.
		for _, want := range []string{
			"Total exported symbols:  11",
			"Documented:              6",
			"Missing documentation:   5",
			"func: Undocumented", "func: Detached", "method: BareMethod",
			"type: Set", "const: Answer",
			"below threshold 80%",
		} {
			if !strings.Contains(out, want) {
				t.Errorf("awk=%q: output missing %q:\n%s", awkBin, want, out)
			}
		}
		// Documented symbols, tests, generated files, unexported names and
		// grouped-block members are never listed as missing.
		for _, name := range []string{"Documented", "TestHelper", "Generated", "unexported", "Grouped", "Block", "MultiLine", "Generic", "Version"} {
			if strings.Contains(out, ": "+name+"\n") {
				t.Errorf("awk=%q: %q should not be listed as missing:\n%s", awkBin, name, out)
			}
		}
		if code != 1 {
			t.Errorf("awk=%q: coverage below threshold should exit 1, got %d", awkBin, code)
		}
	}
}

func TestDocCoverageScript_FullCoveragePasses(t *testing.T) {
	out, code := runDocCoverage(t, map[string]string{
		"b.go": "package b\n\n// Fine is documented.\nfunc Fine() {}\n",
	}, "")
	if code != 0 || !strings.Contains(out, "Documentation coverage: 100.0%") {
		t.Errorf("fully documented package should pass at 100%%, got exit %d:\n%s", code, out)
	}
}
